- src/main/resources/static/css/home.css
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/home.html
- Home 뷰 페이지 구현, Header의 공연 소식/후기 구분
- 실시간 인기 공연
- 글쓰기
- 게시판 미리보기
- Header의 공연 소식/후기 구분
- [ O ] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[Feat] PR 등록`
> [Feat]: Home 뷰 페이지 구현, Header의 공연 소식/후기 구분

- src/main/resources/static/css/home.css
- Home 페이지에 hover 추가
- 게시판 탭
- header의 input
- [ O ] 🔀 PR 제목의 형식을 잘 작성했나요?
> [Style]: Home hover 추가

- src/main/resources/static/css/board/board.css
- src/main/resources/templates/board/board.html
- board 뷰 페이지 구현
- 카테고리 탭
- 글쓰기
- 게시판 미리보기
- 없음
- [ O ] 🔀 PR 제목의 형식을 잘 작성했나요?
> [Feat]: board 뷰 페이지 구현

- src/main/resources/static/css/board/writeform.css
- writeform css 파일 누락으로 인한 재업로드
- writeform css파일
- 없음
- [ O ] 🔀 PR 제목의 형식을 잘 작성했나요?
> [Feat]: writeform css 파일

- src/main/resources/templates/registerform.html
- 회원가입 폼 구현
- html 만 구현한 상태
- 없음
<br>
> [Style]: 회원가입 폼 구현

- src/main/resources/templates/registerform.html
> [Fix]: url 경로 수정

- src/main/resources/static/css/board/board.css
- src/main/resources/static/css/board/writeform.css
- src/main/resources/static/css/home.css
- src/main/resources/templates/fragments/header.html
- Header 프로필 이미지 드롭다운 추가
- Header 프로필 이미지 드롭다운 추가
- Header를 사용하는 모든 css 파일 수정
<br>
- [ O ] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[Feat] PR 등록`
Closes #{이슈 번호}
> [Style]: Header 프로필 이미지 드롭다운 추가

- src/main/resources/templates/loginform.html
- 로그인 폼 네이버 로그인 추가
- html 폼만 구현 상태
- 없음
<br>
> [Feat]: 로그인 폼 네이버 로그인 추가

- src/main/resources/static/css/user/mypage.css
- src/main/resources/templates/user/mypage.html
- Mypage view 구현
- mypage html/css 파일
- 없음
<br>
> [Feat]: Mypage view 구현

- src/main/resources/static/css/loginform.css
- src/main/resources/templates/loginform.html
- loginform css 파일 생성 및 적용
- loginform.css
- loginform.html
<br>
> [Style] loginform css 파일 생성 및 적용

- src/main/java/com/inconcert/domain/like/entity/Like.java
- src/main/java/com/inconcert/domain/like/repository/LikeRepository.java
- src/main/java/com/inconcert/domain/like/service/LikeService.java
- src/main/java/com/inconcert/domain/post/controller/InfoController.java
- src/main/java/com/inconcert/domain/post/controller/InfoRestController.java
- src/main/java/com/inconcert/domain/post/controller/MatchController.java
- src/main/java/com/inconcert/domain/post/controller/MatchRestController.java
- src/main/java/com/inconcert/domain/post/controller/ReviewController.java
- src/main/java/com/inconcert/domain/post/controller/ReviewRestController.java
- src/main/java/com/inconcert/domain/post/controller/TransferController.java
- src/main/java/com/inconcert/domain/post/controller/TransferRestController.java
- src/main/java/com/inconcert/domain/post/entity/Post.java
- src/main/java/com/inconcert/domain/post/service/InfoService.java
- src/main/java/com/inconcert/domain/post/service/MatchService.java
- src/main/java/com/inconcert/domain/post/service/ReviewService.java
- src/main/java/com/inconcert/domain/post/service/TransferService.java
- src/main/java/com/inconcert/domain/user/service/UserService.java
- src/main/java/com/inconcert/global/controller/HomeController.java
- src/main/java/com/inconcert/global/exception/LikeNotFoundException.java
- src/main/java/com/inconcert/global/handler/GlobalExceptionHandler.java
- src/main/resources/static/js/board/post-detail.js
- src/main/resources/templates/board/post-detail.html
- 게시물 좋아요 구현
- 좋아요 클릭시 좋아요 버튼과 좋아요 개수가 동적으로 변함
- 좋아요 여부에 따라 상세페이지 로딩 시 좋아요 버튼이 다르게 보임
- if-elseif-else문 "향상된" switch문으로 변경
- **좋아요 버튼 이쁘게 변경 필요**
<br>
> [Feat]: 게시물 좋아요 구현

- src/main/resources/static/css/registerform.css
- src/main/resources/templates/loginform.html
- src/main/resources/templates/registerform.html
- registerform css 파일 생성 및 적용
- registerform css
- registerform html
<br>
> [Style] registerform css 파일 생성 및 적용

- src/main/java/com/inconcert/domain/like/service/LikeService.java
- src/main/java/com/inconcert/domain/post/controller/InfoRestController.java
- src/main/java/com/inconcert/domain/post/controller/MatchRestController.java
- src/main/java/com/inconcert/domain/post/controller/ReviewRestController.java
- src/main/java/com/inconcert/domain/post/controller/TransferRestController.java
- src/main/java/com/inconcert/global/auth/config/SecurityConfig.java
- src/main/resources/static/css/board/post-detail.css
- src/main/resources/static/js/board/post-detail.js
- src/main/resources/templates/board/post-detail.html
- response의 data를 통한 로그인/로그아웃 확인
- 좋아요 아이콘 버튼 변경
- Font Awesome 라이브러리(아이콘으로 유명한 라이브러리) 추가
- Controller에서 model로 넘겨주던 user를 통한 로그인/로그아웃 확인하는 방법을 response의 data를 통해 확인하는 방법으로 변경
- LikeService에서 중복되는 코드 메소드로 추출
- /api/**로 오는 요청들 permitAll로 변경(추후 보안관련 문제 확인 필요)
- Font Awesome 라이브러리에 부트스트랩과 같이 정의되어있는 클래스명을 추가/삭제를 통해 좋아요 표시
<br>
> [Refactor] response의 data를 통한 로그인/로그아웃 확인

- src/main/java/com/inconcert/global/service/HomeService.java
- src/main/resources/static/css/board/board-detail.css
- 공연 후기에서 게시글 작성자 닉네임 안 보이는 오류
- 없음
- HomeService postDto 빌더내용 변경(username -> nicename)
<br>
> [Fix]: 공연 후기에서 게시글 작성자 닉네임 안 보이는 오류

- src/main/java/com/inconcert/global/controller/HomeController.java
- src/main/resources/static/css/board/board-detail.css
- src/main/resources/static/css/board/post-detail.css
- src/main/resources/static/css/home.css
- src/main/resources/static/css/search-result.css
- src/main/resources/templates/board/board-detail.html
- src/main/resources/templates/board/board.html
- src/main/resources/templates/board/post-detail.html
- src/main/resources/templates/home.html
- src/main/resources/templates/search-result.html
- 검색결과 페이지에 게시판 링크 추가, 머리말 한글로 변경
- 검색결과 페이지에 게시판 링크 추가
- 머리말 한글로 변경
<br>
> [Style]: 검색결과 페이지에 게시판 링크 추가, 머리말 한글로 변경

- src/main/java/com/inconcert/domain/user/controller/UserApiController.java
- src/main/java/com/inconcert/domain/user/controller/UserController.java
- src/main/java/com/inconcert/domain/user/dto/request/FindIdReqDto.java
- src/main/java/com/inconcert/domain/user/repository/UserRepository.java
- src/main/java/com/inconcert/domain/user/service/UserService.java
- src/main/java/com/inconcert/global/auth/config/SecurityConfig.java
- src/main/resources/templates/user/idform.html
- 이름과 이메일 일치 시 아이디 찾기
- idform은 html 만 구현 상태
- 없음
<br>
> [Feat]: 아이디 찾기 추가

- src/main/java/com/inconcert/domain/post/controller/InfoController.java
- src/main/java/com/inconcert/domain/post/controller/MatchController.java
- src/main/java/com/inconcert/domain/post/controller/ReviewController.java
- src/main/java/com/inconcert/domain/post/controller/TransferController.java
- src/main/java/com/inconcert/global/controller/HomeController.java
- src/main/resources/static/css/board/post-detail.css
- src/main/resources/templates/board/board-detail.html
- src/main/resources/templates/board/post-detail.html
- src/main/resources/templates/fragments/header.html
- 게시판 검색 시 검색 정보 불러와서 유지
- 없음
- model에 정보 담아서 불러오는 방법 사용
<br>
> [Style]: 게시판 검색 시 검색 정보 불러와서 유지

- src/main/java/com/inconcert/domain/crawling/entity/Performance.java
- src/main/java/com/inconcert/domain/crawling/service/PerformanceService.java
- src/main/java/com/inconcert/global/service/CrawlingService.java
- 필드가 바뀌어서 저장되는 문제 해결
- 없음
- Build로 생성
<br>
- [ ✅ ] 🔀 PR 제목의 형식을 잘 작성했나요? 
> [Fix]: 필드가 바뀌어서 저장되는 문제 해결

- src/main/java/com/inconcert/domain/comment/controller/CommentController.java
- src/main/java/com/inconcert/domain/comment/dto/CommentCreateForm.java
- src/main/java/com/inconcert/domain/comment/dto/CommentDto.java
- src/main/java/com/inconcert/domain/comment/entity/Comment.java
- src/main/java/com/inconcert/domain/comment/service/InfoCommentService.java
- src/main/java/com/inconcert/domain/crawling/service/PerformanceService.java
- src/main/java/com/inconcert/domain/post/dto/PostDto.java
- src/main/java/com/inconcert/domain/post/entity/Post.java
- src/main/java/com/inconcert/domain/post/service/EditService.java
- src/main/resources/static/css/board/post-detail.css
- src/main/resources/static/js/comment.js
- src/main/resources/templates/board/post-detail.html
- src/main/resources/templates/fragments/commentFragment.html
- 비밀 댓글 기능 추가
- 댓글, 답글 구조 Set -> List 변경
- 비밀 댓글 기능 추가
- 댓글, 답글 구조 변경
<br>
- [ O ] 🔀 PR 제목의 형식을 잘 작성했나요?
> [Feat]: 비밀 댓글 기능 추가

- src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
- src/main/java/com/inconcert/domain/post/service/EditService.java
- src/main/java/com/inconcert/global/controller/HomeController.java
- src/main/java/com/inconcert/global/service/HomeService.java
- src/main/resources/static/css/home.css
- src/main/resources/templates/board/board-detail.html
- src/main/resources/templates/home.html
- /Home에서 postCategory별 인기 공연 하나씩 출력
- db 조회 및 서비스 코드
- 모델로 인기공연 list 넘겨주기
- 마진 수정
<br>
> [Feat]: /Home에서 postCategory별 인기 공연 하나씩 출력

- src/main/resources/static/css/board/board.css
- src/main/resources/static/css/home.css
- src/main/resources/templates/board/board.html
- src/main/resources/templates/home.html
- 게시글 8개만 출력
- 없음
- html switch-case문 수정
<br>
> [Style]: 게시글 8개만 출력

- src/main/java/com/inconcert/domain/post/service/InfoService.java
- src/main/java/com/inconcert/domain/post/service/MatchService.java
- src/main/java/com/inconcert/domain/post/service/ReviewService.java
- src/main/java/com/inconcert/domain/post/service/TransferService.java
- src/main/java/com/inconcert/domain/user/controller/MyPageController.java
- src/main/java/com/inconcert/domain/user/entity/User.java
- src/main/java/com/inconcert/domain/user/repository/MyPageRepostory.java
- src/main/java/com/inconcert/domain/user/service/MyPageService.java
- src/main/java/com/inconcert/domain/user/service/UserService.java
- src/main/java/com/inconcert/global/controller/HomeController.java
- src/main/resources/static/css/user/mypage-detail.css
- src/main/resources/templates/board/board-detail.html
- src/main/resources/templates/board/board.html
- src/main/resources/templates/home.html
- src/main/resources/templates/user/mypage-detail.html
- src/main/resources/templates/user/mypage.html
- 마이페이지 내 글보기, 내 댓글 보기, 좋아요한 글보기, 회원탈퇴 기능 구현
- MyPage 관련 컨트롤러, 서비스, 레포지토리, html/css 파일 생성 및 구현
- 없음
<br>
- [ ✅ ] 🔀 PR 제목의 형식을 잘 작성했나요? 
> [Feat]: 마이페이지 내 글보기, 내 댓글 보기, 좋아요한 글보기, 회원탈퇴 기능 구현

- src/main/java/com/inconcert/domain/user/controller/MyPageController.java
- src/main/java/com/inconcert/domain/user/controller/UserApiController.java
- src/main/java/com/inconcert/domain/user/dto/request/MyPageEditReqDto.java
- src/main/java/com/inconcert/domain/user/dto/request/NicknameCheckReqDto.java
- src/main/java/com/inconcert/domain/user/dto/response/NicknameCheckRspDto.java
- src/main/java/com/inconcert/domain/user/entity/User.java
- src/main/java/com/inconcert/domain/user/repository/UserRepository.java
- src/main/java/com/inconcert/domain/user/service/MyPageService.java
- src/main/java/com/inconcert/domain/user/service/UserService.java
- src/main/java/com/inconcert/global/auth/CustomOAuth2UserService.java
- src/main/java/com/inconcert/global/exception/ResponseCode.java
- src/main/java/com/inconcert/global/exception/ResponseMessage.java
- src/main/resources/static/css/user/editform.css
- src/main/resources/templates/user/mypage.html
- src/main/resources/templates/user/mypageedit.html
- 내 정보 수정 기능
- 내용을 적어주세요. (없으면 `없음` 기재)
- OAuth2 로그인 시 임의로 비밀번호 지정하여 NPE 발생하지 않게 함
- 중복 닉네임이나 이메일 입력 시 제출되지 않게 함
<br>
> [Feat]: 내 정보 수정 기능

- src/main/java/com/inconcert/domain/comment/entity/Comment.java
- src/main/java/com/inconcert/domain/post/service/InfoService.java
- src/main/java/com/inconcert/domain/post/service/MatchService.java
- src/main/java/com/inconcert/domain/post/service/ReviewService.java
- src/main/java/com/inconcert/domain/post/service/TransferService.java
- src/main/java/com/inconcert/global/service/CrawlingService.java
- src/main/resources/static/css/board/post-detail.css
- src/main/resources/static/js/profile.js
- src/main/resources/templates/board/post-detail.html
- src/main/resources/templates/fragments/commentFragment.html
- 유저 프로필 팝업 추가
- 유저 프로필 팝업 추가(게시글 내에서 게시글 작성자/댓글 작성자의 프로필 이미지를 클릭하면 팝업 생김)
- PostService의 postDto 값에 user 추가 => html에서 user 정보 사용을 위해
- 비밀 댓글 기능 버그 수정
=> 비밀 댓글 작성 후 수정을 눌렀을 때 비밀 댓글 체크박스 항상 false였던 버그 / 현재 상태에 따라 반영되도록 수정
<br>
> [Feat]: 유저 프로필 팝업 추가

- src/main/java/com/inconcert/domain/comment/repository/CommentRepository.java
- src/main/java/com/inconcert/domain/comment/service/MatchCommentService.java
- src/main/java/com/inconcert/domain/comment/service/ReviewCommentService.java
- src/main/java/com/inconcert/domain/comment/service/TransferCommentService.java
- src/main/java/com/inconcert/domain/post/service/MatchService.java
- src/main/java/com/inconcert/domain/post/service/ReviewService.java
- src/main/java/com/inconcert/domain/post/service/TransferService.java
- src/main/resources/application.yml
- src/main/resources/static/css/board/post-detail.css
- src/main/resources/static/css/findform.css
- src/main/resources/static/css/user/editform.css
- src/main/resources/static/js/comment.js
- src/main/resources/static/js/profile.js
- src/main/resources/templates/board/post-detail.html
- src/main/resources/templates/fragments/commentFragment.html
- src/main/resources/templates/user/findpwform.html
- src/main/resources/templates/user/idform.html
- src/main/resources/templates/user/mypageedit.html
- 댓글 정렬 기능 추가
- 아이디/비밀번호 찾기 css 추가
- 댓글 등록순/최신순 정렬 기능 추가
- 아이디/비밀번호 찾기 css 추가
- 프로필 팝업 열고 닫기 버그 수정 및 성능 개선
<br>
> [Feat]: 댓글 등록순/최신순 정렬 추가

- src/main/java/com/inconcert/domain/comment/controller/CommentController.java
- 게시글 작성자도 댓글 삭제할 수 있도록 수정
- 없음
- 댓글 작성자 뿐만 아니라 게시글 작성자도 댓글을 삭제할 수 있도록 수정
<br>
> [Fix]: 댓글 삭제 수정

- src/main/java/com/inconcert/domain/user/controller/UserController.java
- src/main/java/com/inconcert/domain/user/service/UserService.java
- src/main/resources/static/css/board/post-detail.css
- src/main/resources/templates/fragments/commentFragment.html
- src/main/resources/templates/loginform.html
- src/main/resources/templates/registerform.html
- src/main/resources/templates/user/findidform.html
- src/main/resources/templates/user/findpwform.html
- 회원가입 이메일 인증 시 알림 창 중복 출력 제거 
- 없음
- redirect 로그인 폼 수정
- 댓글 프로필 보기 css 오류 해결 추가
<br>
> [Refactor]: 회원가입 이메일 인증 시 알림 창 중복 출력 제거 

- src/main/java/com/inconcert/global/auth/config/SecurityConfig.java
- src/main/java/com/inconcert/global/auth/filter/JwtAuthenticationFilter.java
- src/main/java/com/inconcert/global/exception/ExceptionMessage.java
- src/main/java/com/inconcert/global/handler/CustomOAuth2AuthenticationFailureHandler.java
- src/main/java/com/inconcert/global/handler/GlobalExceptionHandler.java
- 에러 발생 시 네이버 로그인 창으로 이동하지 않게 수정
- 없음
- 없음
<br>
> [Fix]: 에러 처리 추가

- src/main/java/com/inconcert/domain/post/controller/InfoController.java
- src/main/java/com/inconcert/domain/post/controller/MatchController.java
- src/main/java/com/inconcert/domain/post/controller/ReviewController.java
- src/main/java/com/inconcert/domain/post/controller/TransferController.java
- src/main/java/com/inconcert/domain/post/service/InfoService.java
- src/main/java/com/inconcert/domain/post/service/MatchService.java
- src/main/java/com/inconcert/domain/post/service/ReviewService.java
- src/main/java/com/inconcert/domain/post/service/TransferService.java
- src/main/resources/templates/notification.html
- 게시물 작성 리다이렉트 변경, 알림 실시간 오류 해결
- 없음
- 게시물 작성 리다이렉트 변경
- 알림 실시간 오류 해결
<br>
Closes #{이슈 번호}
> [Refactor]: 게시물 작성 리다이렉트 변경, 알림 실시간 오류 해결

- src/main/java/com/inconcert/domain/post/controller/MatchController.java
- src/main/java/com/inconcert/domain/post/repository/MatchRepository.java
- src/main/java/com/inconcert/domain/post/service/EditService.java
- src/main/java/com/inconcert/domain/post/service/MatchService.java
- src/main/java/com/inconcert/domain/post/service/WriteService.java
- src/main/resources/templates/board/board-detail.html
- src/main/resources/templates/board/editform.html
- 글 작성 및 수정 시 종료날짜 못 불러오는 오류 해결
- 동행 게시판의 경우 MBTI, 성별 검색 필터 추가
- 동행 게시판 검색 필터에 성별, MBTI 추가
- EditService에서 .getTitle() 추가
<br>
> [Fix]: 글 작성 및 수정 시 종료날짜 못 불러오는 오류 해결, 동행 게시판의 경우 MBTI, 성별 검색 필터 추가

- src/main/java/com/inconcert/domain/user/controller/UserApiController.java
- src/main/java/com/inconcert/domain/user/dto/request/PhoneNumberCheckReqDto.java
- src/main/java/com/inconcert/domain/user/dto/request/RegisterReqDto.java
- src/main/java/com/inconcert/domain/user/dto/response/PhoneNumberCheckRspDto.java
- src/main/java/com/inconcert/domain/user/repository/UserRepository.java
- src/main/java/com/inconcert/domain/user/service/UserService.java
- src/main/java/com/inconcert/global/exception/ResponseCode.java
- src/main/java/com/inconcert/global/exception/ResponseMessage.java
- src/main/resources/static/css/registerform.css
- src/main/resources/templates/registerform.html
- 회원가입 시 유효성 검사 불만족할 때 html 화면에 빨간색 오류 메시지 띄우기
- phoneNumber에 10-11자리의 숫자만 입력하게 함 
- birth에서 생년월일을 입력할 때 오늘 이후의 날짜는 선택하지 못하게 함
- 개인정보 이용 동의 버튼을 필수로 눌러야 회원가입 가능하게 함
- phoneNumber, nickname, username 이 중복된다면 칸 아래 에러 문구가 뜨게 함
- username은 알파벳, 숫자가 필수로 포함, 5자 이상으로 하고 불만족 시 칸 아래 에러 문구가 뜨게 함
- password는 알파벳, 숫자, 특수기호가 필수로 포함, 8자 이상으로 하고 불만족 시 칸 아래 에러 문구가 뜨게 함
- 없음
<br>
> [Feat]: 회원가입 시 유효성 검사 추가

- src/main/java/com/inconcert/domain/certification/entity/Certification.java
- src/main/java/com/inconcert/domain/user/dto/request/EmailCertificationReqDto.java
- src/main/java/com/inconcert/domain/user/dto/request/RegisterReqDto.java
- src/main/java/com/inconcert/domain/user/dto/response/RegisterRspDto.java
- src/main/java/com/inconcert/domain/user/service/UserService.java
- src/main/java/com/inconcert/global/exception/ResponseCode.java
- src/main/java/com/inconcert/global/exception/ResponseMessage.java
- src/main/resources/static/js/register.js
- src/main/resources/templates/registerform.html
- 회원가입 유효성 검사 및 인증번호 관련 문제 해결
- 비밀번호 확인, 이메일, 이름, 핸드폰 번호 유효성 검사
- 인증번호 여러 번 보내면 update
- 인증번호 확인 완료 후 아이디를 수정하면 이메일 재인증 메시지 출력 -> 다시 인증을 완료하면 삭제
<br>
> [Refactor]: 회원가입 유효성 검사 및 인증번호 관련 문제 해결

- src/main/resources/static/js/board/post-detail.js
- src/main/resources/static/js/chat/chat.js
- src/main/resources/templates/chat/room.html
- 1:1 채팅 요청이 안 되는 문제 해결
- 1:1 채팅 JS 메소드 추가
- 1:1 채팅인 경우 유저 목록만 출력
<br>
> [Fix]: 1:1 채팅이 안 되는 문제 해결

- src/main/resources/static/js/chat/chat.js
- 사용하지 않는 메서드 삭제
- 없음
- chat.js 의 fetchNotificationsFromServer 메서드 삭제
<br>
> [Chore] : 사용하지 않는 메서드 삭제

- src/main/java/com/inconcert/domain/comment/controller/CommentController.java
- src/main/java/com/inconcert/domain/comment/service/CommentService.java
- src/main/java/com/inconcert/domain/comment/service/InfoCommentService.java
- src/main/java/com/inconcert/domain/comment/service/MatchCommentService.java
- src/main/java/com/inconcert/domain/comment/service/ReviewCommentService.java
- src/main/java/com/inconcert/domain/comment/service/TransferCommentService.java
- 본인이 작성한 댓글이 알림 오는 문제 해결
- 없음
- 필요없는 메소드 삭제
- Service에서 알림을 보낼 때 본인이 작성한 건지 확인하여 알림 전송
<br>
- [ ✅  ] 🧹 불필요한 코드는 제거했나요?
- [ ✅  ] 💭 (선택) 이슈는 등록했나요?
- [ ✅  ] 🏷️ 라벨은 등록했나요?
> [Fix]: 본인이 작성한 댓글에 알림 오는 문제 해결

- src/main/java/com/inconcert/domain/feedback/entity/Feedback.java
- src/main/java/com/inconcert/domain/feedback/service/FeedbackService.java
- src/main/java/com/inconcert/domain/post/repository/MatchRepository.java
- src/main/java/com/inconcert/domain/user/entity/User.java
- src/main/java/com/inconcert/domain/user/repository/UserRepository.java
- src/main/java/com/inconcert/domain/user/service/MyPageService.java
- src/main/resources/templates/board/post-detail.html
- src/main/resources/templates/fragments/commentFragment.html
- src/main/resources/templates/user/mypage.html
- 상호 평가 시 매너점수에 반영 로직 추가
- 피드백 작성 시 매너점수 계산하는 로직 추가
- 매너점수 출력하는 부분에 null처리 추가
- 게시글 작성자만 평가 가능하던 문제 해결
- 동행완료 버튼은 동행 게시판에만 나타나게 수정
<br>
- [ ✅ ]🧹 불필요한 코드는 제거했나요?
- [ ✅ ]💭 (선택) 이슈는 등록했나요?
> [Feat]: 상호 평가 시 매너점수에 반영 로직 추가

- src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
- IncorrectResultSizeDataAccessException 문제 해결
- 없음
- 단일 결과 쿼리에서 복수의 쿼리가 조회되는 문제 해결
<br>
> [Fix]: IncorrectResultSizeDataAccessException 문제 해결

- build.gradle
- src/main/java/com/inconcert/global/auth/config/SecurityConfig.java
- src/main/java/com/inconcert/global/swagger/OpenAPIConfig.java
- src/main/resources/application.yml
- src/test/java/com/inconcert/domain/comment/CommentControllerTest.java
- src/test/java/com/inconcert/domain/post/InfoControllerTest.java
- src/test/java/com/inconcert/domain/post/MatchControllerTest.java
- 댓글/게시글 컨트롤러 테스트 코드 작성
- 댓글/대댓글 CRUD, 예외 상황에 대한 테스트 코드 작성
- 게시글 CRUD, 예외 상황에 대한 테스트 코드 작성
- 없음
<br>
Closes #{이슈 번호}
> [Test]: 댓글/게시글 컨트롤러 테스트 코드 작성

- src/main/java/com/inconcert/domain/images/controller/ImageApiController.java
- src/main/java/com/inconcert/domain/images/service/ImageService.java
- src/main/java/com/inconcert/domain/post/controller/ImageController.java
- src/main/java/com/inconcert/domain/post/controller/InfoController.java
- src/main/java/com/inconcert/domain/post/controller/MatchController.java
- src/main/java/com/inconcert/domain/post/controller/ReviewController.java
- src/main/java/com/inconcert/domain/post/controller/TransferController.java
- src/main/java/com/inconcert/domain/post/entity/Post.java
- src/main/java/com/inconcert/domain/post/service/ImageService.java
- src/main/java/com/inconcert/domain/post/service/ReviewService.java
- src/main/java/com/inconcert/domain/post/service/WriteService.java
- src/main/java/com/inconcert/domain/scraping/service/PerformanceService.java
- src/main/java/com/inconcert/domain/user/service/MyPageService.java
- src/main/resources/application.yml
- src/main/resources/templates/board/writeform.html
- src/test/java/com/inconcert/domain/post/controller/InfoControllerTest.java
- 포스트 작성 이미지 처리
- 글이 작성되면 S3에 이미지 업로드
- 글이 다 작성되어야만 업로드 되게 수정
<br>
> [Feat]: 글 작성 이미지 처리

- src/main/java/com/inconcert/common/controller/ImageApiController.java
- src/main/java/com/inconcert/common/service/ImageService.java
- src/main/java/com/inconcert/domain/post/service/ReviewService.java
- src/main/java/com/inconcert/domain/user/service/MyPageService.java
- src/main/resources/templates/board/writeform.html
- 이미지 규격(가로x세로)이 넘어가면 MaxUploadSizeExceededException 오류나는 부분 리사이징을 통해 해결
- writeform.html에 리사이징 함수 해결
- 코드 메소드로 분리
<br>
> [Fix]: 이미지 규격(가로x세로)이 넘어가면 MaxUploadSizeExceededException 오류나는 부분 리사이징을 통해 해결

- src/main/java/com/inconcert/common/service/ImageService.java
- src/main/java/com/inconcert/domain/post/service/MatchService.java
- src/main/java/com/inconcert/domain/post/service/TransferService.java
- src/main/resources/templates/board/writeform.html
- 글 삭제 시 S3 버킷의 이미지도 함께 삭제 기능 추가
- 없음
- 없음
<br>
> [Feat]: 글 삭제 시 S3 버킷의 이미지도 함께 삭제 기능 추가

- src/main/java/com/inconcert/common/controller/ImageApiController.java
- src/main/java/com/inconcert/common/service/ImageService.java
- src/main/java/com/inconcert/domain/post/controller/InfoController.java
- src/main/java/com/inconcert/domain/post/controller/ReviewController.java
- src/main/java/com/inconcert/domain/post/service/EditService.java
- src/main/java/com/inconcert/domain/post/service/WriteService.java
- src/main/java/com/inconcert/domain/user/service/MyPageService.java
- src/main/resources/templates/board/editform.html
- src/main/resources/templates/board/writeform.html
- src/main/resources/templates/user/mypageedit.html
- 게시글 작성 시 이미지 지우면 s3에서도 지워지게 추가, 게시글 작성 취소 시 업로드한 사진 제거
- 자바스크립트의 전체적인 주석 추가
- 사진 제거 관련 컨트롤러, 서비스 코드 추가
- 모든 s3 관련 로직 글 작성 및 수정 시에만 실행
- 게시글을 작성하지 않고 창을 닫거나 다른 페이지로 가는 경우 크롬 기능인 "사이트에서 나가시겠습니까?" 띄우기
- 마이페이지 프로필 변경 s3 관련 로직 추가
- 이미지 업로드 1개씩 하므로, uploadImages -> uploadImage로 변경
<br>
> [Feat]: 게시글 작성 시 이미지 지우면 s3에서도 지워지게 추가, 게시글 작성 취소 시 업로드한 사진 제거

- src/test/java/com/inconcert/domain/chat/ChatApiControllerTest.java
- src/test/java/com/inconcert/domain/chat/ChatControllerTest.java
- src/test/java/com/inconcert/domain/chat/ChatNotificationControllerTest.java
- src/test/java/com/inconcert/domain/chat/ChatWebSocketControllerTest.java
- src/test/java/com/inconcert/domain/comment/controller/CommentControllerTest.java
- src/test/java/com/inconcert/domain/post/controller/InfoControllerTest.java
- src/test/java/com/inconcert/domain/post/controller/MatchControllerTest.java
- Chat 컨트롤러 테스트 코드 작성
- Chat 컨트롤러 테스트 코드 작성
- 없음
<br>
> [Test]: Chat 컨트롤러 테스트 코드 작성

- build.gradle
- src/main/java/com/inconcert/common/controller/HomeApiController.java
- src/main/java/com/inconcert/common/controller/HomeController.java
- src/main/java/com/inconcert/common/service/HomeService.java
- src/main/java/com/inconcert/common/service/ImageService.java
- src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
- src/main/java/com/inconcert/domain/post/service/ReviewService.java
- src/test/java/com/inconcert/common/service/HomeServiceTest.java
- src/test/java/com/inconcert/common/service/ImageServiceTest.java
- HomeService, ImageService 테스트 코드 작성
- HomeServiceTest, ImageServiceTest
- 메소드명 수정
- ReviewService에  s3 삭제 로직 제거 후, ImageService의 메소드 사용으로 변경
<br>
> [Test]: HomeService, ImageService 테스트 코드 작성

- build.gradle
- src/main/java/com/inconcert/domain/like/service/LikeService.java
- src/main/java/com/inconcert/domain/post/entity/Post.java
- src/main/java/com/inconcert/domain/report/repository/ReportRepository.java
- src/main/java/com/inconcert/domain/report/service/ReportService.java
- src/test/java/com/inconcert/domain/like/controller/LikeRestControllerTest.java
- src/test/java/com/inconcert/domain/like/service/LikeServiceTest.java
- src/test/java/com/inconcert/domain/report/controller/ReportControllerTest.java
- src/test/java/com/inconcert/domain/report/service/ReportServiceTest.java
- Like, Report 테스트 코드 작성
- Post에 Report 관련 Cascade 추가
- 의존성 중복된 부분 삭제
- Long 타입 비교 부분 equals로 수정
- Transaction 안에 Transaction 있던 문제 해결
<br>
> [Test]: Like, Report 테스트 코드 작성

- src/main/java/com/inconcert/domain/like/entity/Like.java
- src/main/java/com/inconcert/domain/post/entity/Post.java
- src/main/java/com/inconcert/domain/user/entity/User.java
- src/test/java/com/inconcert/domain/user/service/MyPageServiceTest.java
- MyPageService 단위 테스트 코드 작성
- 없음
- 없음
<br>
- [ ✅  ] 💯 (선택) 테스트는 잘 통과했나요?
- [ ✅  ] 💭 (선택) 이슈는 등록했나요?
> [Test]: MyPageService 단위 테스트 코드 작성

- src/main/java/com/inconcert/domain/comment/entity/Comment.java
- src/test/java/com/inconcert/domain/notification/NotificationControllerTest.java
- 알림 컨트롤러 테스트 코드 작성
- 알림 컨트롤러 테스트 코드 작성
- 없음
<br>
> [Test]: 알림 컨트롤러 테스트 코드 작성

- src/main/java/com/inconcert/domain/user/dto/request/EmailCertificationReqDto.java
- src/main/java/com/inconcert/domain/user/dto/request/EmailCheckReqDto.java
- src/main/java/com/inconcert/domain/user/dto/request/FindIdReqDto.java
- src/main/java/com/inconcert/domain/user/dto/request/FindPasswordReqDto.java
- src/main/java/com/inconcert/domain/user/dto/request/NicknameCheckReqDto.java
- src/main/java/com/inconcert/domain/user/dto/request/PhoneNumberCheckReqDto.java
- src/main/java/com/inconcert/domain/user/dto/request/RegisterReqDto.java
- src/main/java/com/inconcert/domain/user/dto/request/UsernameCheckReqDto.java
- src/main/java/com/inconcert/domain/user/entity/User.java
- src/main/java/com/inconcert/domain/user/service/UserService.java
- src/test/java/com/inconcert/common/service/HomeServiceTest.java
- src/test/java/com/inconcert/common/service/ImageServiceTest.java
- src/test/java/com/inconcert/domain/user/service/UserServiceTest.java
- UserService test 로직 작성
- DTO에 Builder 추가
- User 엔티티에 생성자 추가
- Home/ImageServiceTest 수정
<br>
> [Test]: UserService test 로직 작성

- src/main/java/com/inconcert/common/service/HomeService.java
- src/main/java/com/inconcert/domain/post/entity/Post.java
- src/main/java/com/inconcert/domain/post/repository/InfoRepository.java
- src/main/java/com/inconcert/domain/scraping/service/PerformanceService.java
- src/test/java/com/inconcert/common/service/HomeServiceTest.java
- 공연 소식 게시글에 popularity 생성해 인기순위 알고리즘 적용
- popularity 필드 추가
- 알고리즘 추가
- 공연 소식 저장하는 방식 수정
<br>
> [Chore]: 공연 소식 게시글에 popularity 생성해 인기순위 알고리즘 적용
